src/Entity/MgCarriers.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MgCarriersRepository")
 */
class MgCarriers
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $carrier_name;

    /**
     * @ORM\Column(type="boolean", options={"default": true})
     */
    private $carrier_active;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     *
     * @Assert\File(mimeTypes={
     *     "image/png",
     *     "image/jpeg",
     *     "image/jpg",
     *     "image/gif",
     * })
     */
    private $carrier_logo;

    /**
     * @ORM\Column(type="boolean")
     */
    private $carrier_default;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MgCarriersLang", mappedBy="carrier", orphanRemoval=true)
     */
    private $carriersLang;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\MgCarriersConfig", mappedBy="carrier", cascade={"persist", "remove"})
     */
    private $config;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MgProducts", mappedBy="carrier")
     */
    private $products;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MgOrdersCarriers", mappedBy="carrier")
     */
    private $orderCarriers;

    public function __construct()
    {
        $this->carriersLang = new ArrayCollection();
        $this->products = new ArrayCollection();
        $this->orderCarriers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCarrierName(): ?string
    {
        return $this->carrier_name;
    }

    public function setCarrierName(string $carrier_name): self
    {
        $this->carrier_name = $carrier_name;

        return $this;
    }

    public function getCarrierActive(): ?bool
    {
        return $this->carrier_active;
    }

    public function setCarrierActive(bool $carrier_active): self
    {
        $this->carrier_active = $carrier_active;

        return $this;
    }

    public function getCarrierLogo()
    {
        return $this->carrier_logo;
    }

    public function setCarrierLogo($carrier_logo): self
    {
        $this->carrier_logo = $carrier_logo;

        return $this;
    }

    public function getCarrierDefault(): ?bool
    {
        return $this->carrier_default;
    }

    public function setCarrierDefault(bool $carrier_default): self
    {
        $this->carrier_default = $carrier_default;

        return $this;
    }

    /**
     * @return Collection|MgCarriersLang[]
     */
    public function getCarriersLang(): Collection
    {
        return $this->carriersLang;
    }

    public function addCarriersLang(MgCarriersLang $carriersLang): self
    {
        if (!$this->carriersLang->contains($carriersLang)) {
            $this->carriersLang[] = $carriersLang;
            $carriersLang->setCarrier($this);
        }

        return $this;
    }

    public function removeCarriersLang(MgCarriersLang $carriersLang): self
    {
        if ($this->carriersLang->contains($carriersLang)) {
            $this->carriersLang->removeElement($carriersLang);
            // set the owning side to null (unless already changed)
            if ($carriersLang->getCarrier() === $this) {
                $carriersLang->setCarrier(null);
            }
        }

        return $this;
    }

    public function getConfig(): ?MgCarriersConfig
    {
        return $this->config;
    }

    public function setConfig(MgCarriersConfig $config): self
    {
        $this->config = $config;

        // set the owning side of the relation if necessary
        if ($config->getCarrier() !== $this) {
            $config->setCarrier($this);
        }

        return $this;
    }

    /**
     * @return Collection|MgProducts[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(MgProducts $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setCarrier($this);
        }

        return $this;
    }

    public function removeProduct(MgProducts $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getCarrier() === $this) {
                $product->setCarrier(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|MgOrdersCarriers[]
     */
    public function getOrderCarriers(): Collection
    {
        return $this->orderCarriers;
    }

    public function addOrderCarrier(MgOrdersCarriers $orderCarrier): self
    {
        if (!$this->orderCarriers->contains($orderCarrier)) {
            $this->orderCarriers[] = $orderCarrier;
            $orderCarrier->setCarrier($this);
        }

        return $this;
    }

    public function removeOrderCarrier(MgOrdersCarriers $orderCarrier): self
    {
        if ($this->orderCarriers->contains($orderCarrier)) {
            $this->orderCarriers->removeElement($orderCarrier);
            // set the owning side to null (unless already changed)
            if ($orderCarrier->getCarrier() === $this) {
                $orderCarrier->setCarrier(null);
            }
        }

        return $this;
    }
}

src/Entity/MgGenders.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MgGendersRepository")
 */
class MgGenders
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\MgLanguages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $lang;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $short_gender;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $name_gender;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MgUsers", mappedBy="gender")
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MgCustomersAddresses", mappedBy="gender")
     */
    private $customersAddresses;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->customersAddresses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLang(): ?MgLanguages
    {
        return $this->lang;
    }

    public function setLang(?MgLanguages $lang): self
    {
        $this->lang = $lang;

        return $this;
    }

    public function getShortGender(): ?string
    {
        return $this->short_gender;
    }

    public function setShortGender(string $short_gender): self
    {
        $this->short_gender = $short_gender;

        return $this;
    }

    public function getNameGender(): ?string
    {
        return $this->name_gender;
    }

    public function setNameGender(string $name_gender): self
    {
        $this->name_gender = $name_gender;

        return $this;
    }

    /**
     * @return Collection|MgUsers[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(MgUsers $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setGender($this);
        }

        return $this;
    }

    public function removeUser(MgUsers $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            // set the owning side to null (unless already changed)
            if ($user->getGender() === $this) {
                $user->setGender(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|MgCustomersAddresses[]
     */
    public function getCustomersAddresses(): Collection
    {
        return $this->customersAddresses;
    }

    public function addCustomersAddress(MgCustomersAddresses $customersAddress): self
    {
        if (!$this->customersAddresses->contains($customersAddress)) {
            $this->customersAddresses[] = $customersAddress;
            $customersAddress->setGender($this);
        }

        return $this;
    }

    public function removeCustomersAddress(MgCustomersAddresses $customersAddress): self
    {
        if ($this->customersAddresses->contains($customersAddress)) {
            $this->customersAddresses->removeElement($customersAddress);
            // set the owning side to null (unless already changed)
            if ($customersAddress->getGender() === $this) {
                $customersAddress->setGender(null);
            }
        }

        return $this;
    }
}

templates/main/cart/confirmCart.html.twig
{% extends 'base.html.twig' %}

{% block title %}Votre panier d'achat{% endblock %}
{% block introHome %}{% endblock %}

{% block main %}
	<div id="infobox">
		<div id="closeInfobox"></div>
		<h1>Conditions générales de vente</h1>
		<div id="contentInfobox">
			{{ cgv|raw }}
		</div>
	</div>
	<div id="mainContent">
		<h1>Confirmation de votre commande</h1>
		{% for label, messages in app.flashes %}
			{% for message in messages %}
				<div class="alert alert-{{label}}">
					{{message|raw}}
				</div>
			{% endfor %}
		{% endfor %}
		{% if cart|length > 0 %}	<div id="carnetAdresse" class="clearfix">
	<table id="verifAdresse">
		<thead>
			<tr>
				<th style="text-align: left;">Livraison</th>
				</tr>
		</thead>
		<tfoot>
			<tr>
				<td><a href="compte/modif-adresse-livraison.php">Modifier</a></td>
				</tr>
		</tfoot>
		<tbody>
			<tr>
				<td>
					{% for gender in genders %}{% if gender.id == shippingAddress.gender.id %}{{ gender.shortGender }}{% endif %}{% endfor %} {{ shippingAddress.addressFirstname }} {{ shippingAddress.addressLastname }}<br />
					{{ shippingAddress.address|nl2br }}<br />
					{{ shippingAddress.zipcode }} {{ shippingAddress.town }}
				</td>
				</tr>
		</tbody>
	</table>
	<table id="verifAdresse">
		<thead>
			<tr>
				<th>Facturation</th>
				</tr>
		</thead>
		<tfoot>
			<tr>
				<td><a href="compte/modif-adresse-facturation.php">Modifier</a></td>
			</tr>
		</tfoot>
		<tbody>
			<tr>
				<td>
					{% for gender in genders %}{% if gender.id == billingAddress.gender.id %}{{ gender.shortGender }}{% endif %}{% endfor %} {{ billingAddress.addressFirstname }} {{ billingAddress.addressLastname }}<br />
					{{ billingAddress.address|nl2br }}<br />
					{{ billingAddress.zipcode }} {{ billingAddress.town }}
				</td>
			</tr>
		</tbody>
	</table>
	</div>
			<table id="contenuPanier">
				<thead>
					<tr class="title-top">
						<th>&nbsp;</th>
						<th style="text-align: center">Produit</th>
						<th>Prix Unitaire</th>
						<th>Quantité</th>
						<th>Total</th>
						<th>&nbsp;</th>				
					</tr>
				</thead>
				<tbody>
					{% for key, item in cart %}
					<tr>
						<td class="product-thumbnail">
							{% if key in images|keys %}
							<img src="{{ asset('img/p/') ~ images[key] }}" alt="{{ item.title }}">
							{% else %}
							<img src="{{ asset('img/p/fr.jpg') }}" alt="{{ item.title }}">
							{% endif %}
						</td>
						<td style="text-align: center;">
							<strong>{{ item.title }}</strong>
						</td>
						<td class="product-price">
							{% if item.amount['grossPriceAllTaxes'] != item.amount['priceNetAllTaxes'] %}
							<span class="price">
								<span style="text-decoration: line-through; font-size: 0.80em; color: #aaa;">{{ item.amount['grossPriceAllTaxes']|number_format(2, ',', ' ') }} €</span>
								{{ item.amount['priceNetAllTaxes']|number_format(2, ',', ' ') }} €
							</span>
							{% else %}
								<span class="price">{{ item.amount['priceNetAllTaxes']|number_format(2, ',', ' ') }} €</span>
							{% endif %}
						</td>
						<td class="product-quantity">
							{{ item.qty }}
						</td>
						<td class="product-subtotal">{{ (item.amount['priceNetAllTaxes'] * item.qty)|number_format(2, ',', ' ') }} €</td>
						<td class="product-remove"><a href="{{ path('cart_dell_line', {'id' : key}) }}"><img src="{{ asset('img/delete.png') }}" width="13" height="16"></a></td>
					</tr>
					{% endfor %}
				</tbody>
				<tfoot>
					<tr>
						<td></td>
						<td></td>
						<td class="prixTotal" colspan="2" style="text-align: right;">Montant total</td>
						<td class="prixTotal">{{ cartService.totalCart|number_format(2, ',', ' ') }}&nbsp;€</td>
					</tr>
					{% set totalShipping = 0 %}
					{% for cartShipping in shipping %}
					{% set totalShipping = totalShipping + cartShipping['price'] + cartShipping['taxes'] %}
					<tr>
						<td></td>
						<td colspan="3" style="text-align: right;">Livraison {{ carriers[loop.index].carrierName }}</td>
						<td>{{ (cartShipping['price']+cartShipping['taxes'])|number_format(2, ',', ' ') }}&nbsp;€</td>
					</tr>
					{% endfor %}
					<tr>
						<td></td>
						<td></td>
						<td class="prixTotal" colspan="2" style="text-align: right;"><strong>Total commande</strong></td>
						<td class="prixTotal">{{ (cartService.totalCart + totalShipping)|number_format(2, ',', ' ') }}&nbsp;€<td>
					</tr>
					<tr>
						<td colspan="6" style="text-align: left; background-color: #f2f2f2;">
						<form name="form1" method="post" action="">
							<input type="checkbox" name="accept_cgv" id="accept_cgv">
							<label for="accept_cgv">Je déclare avoir pris connaissance des <a href="{{ path('page', {'slug': 'conditions-generales-de-vente'}) }}" id="open-infobox">conditions générales de vente</a></label>
						</form>
						</td>
					</td>
				</tfoot>
			</table>
		<div class="choosePayment">
			{% if app.user.customers.addresses|length > 0 %}
			<p><strong>Veuillez choisir un mode de paiement ci-dessous :</strong></p>
			<table id="moyenPaiement">
			    {% for payment in payments %}
			    <tr>
			        <td><span class="moyenPaiementImg"><img src="{{ asset('img/payments/') }}{{ payment.logo }}" alt="" /></span></td>
			        <td><span class="moyenPaiementTitre">{{ payment.title }}</span><span class="moyenPaiementDescription">{{ payment.description }}</span></td>
			        <td>
				       	<div class="valideCommande">
			               	<p><a href="{{ path('payment_valid', {'mode': payment.type}) }}" class="btn btn-primary">Choisir ce mode de paiement &raquo;</a></p>
			           	</div>
			        </td>
			    </tr>
			    {% endfor %}
			</table>
			{% endif %}
		</div>
		{% else %}
		<div>
			<p colspan="6">Votre panier est vide.</p>
		</div>
		{% endif %}
	</div>
{% endblock %}
{% block javascripts %}
	<script type="text/javascript" src="{{ asset('js/accept_cgv.js') }}"></script>
	<script>
	acceptCgv('valideCommande', 'accept_cgv');
	</script>
{% endblock %}

templates/main/cart/confirmCartPayment.html.twig
{% extends 'base.html.twig' %}

{% block title %}Votre panier d'achat{% endblock %}
{% block introHome %}{% endblock %}

{% block main %}
	<div id="mainContent">
		<h1>Confirmation de votre commande</h1>
		{% for label, messages in app.flashes %}
			{% for message in messages %}
				<div class="alert alert-{{label}}">
					{{message|raw}}
				</div>
			{% endfor %}
		{% endfor %}
		{% if cart|length > 0 %}	<div id="carnetAdresse" class="clearfix">
	<table id="verifAdresse">
		<thead>
			<tr>
				<th style="text-align: left;">Livraison</th>
				</tr>
		</thead>
		<tfoot>
			<tr>
				<td><a href="compte/modif-adresse-livraison.php">Modifier</a></td>
				</tr>
		</tfoot>
		<tbody>
			<tr>
				<td>
					{% for gender in genders %}{% if gender.id == shippingAddress.gender.id %}{{ gender.shortGender }}{% endif %}{% endfor %} {{ shippingAddress.addressFirstname }} {{ shippingAddress.addressLastname }}<br />
					{{ shippingAddress.address|nl2br }}<br />
					{{ shippingAddress.zipcode }} {{ shippingAddress.town }}
				</td>
				</tr>
		</tbody>
	</table>
	<table id="verifAdresse">
		<thead>
			<tr>
				<th>Facturation</th>
				</tr>
		</thead>
		<tfoot>
			<tr>
				<td><a href="compte/modif-adresse-facturation.php">Modifier</a></td>
			</tr>
		</tfoot>
		<tbody>
			<tr>
				<td>
					{% for gender in genders %}{% if gender.id == billingAddress.gender.id %}{{ gender.shortGender }}{% endif %}{% endfor %} {{ billingAddress.addressFirstname }} {{ billingAddress.addressLastname }}<br />
					{{ billingAddress.address|nl2br }}<br />
					{{ billingAddress.zipcode }} {{ billingAddress.town }}
				</td>
			</tr>
		</tbody>
	</table>
	</div>
			<table id="contenuPanier">
				<thead>
					<tr class="title-top">
						<th>&nbsp;</th>
						<th style="text-align: center">Produit</th>
						<th>Prix Unitaire</th>
						<th>Quantité</th>
						<th>Total</th>
						<th>&nbsp;</th>				
					</tr>
				</thead>
				<tbody>
					{% for key, item in cart %}
					<tr>
						<td class="product-thumbnail">
							{% if key in images|keys %}
							<img src="{{ asset('img/p/') ~ images[key] }}" alt="{{ item.title }}">
							{% else %}
							<img src="{{ asset('img/p/fr.jpg') }}" alt="{{ item.title }}">
							{% endif %}
						</td>
						<td style="text-align: center;">
							<strong>{{ item.title }}</strong>
						</td>
						<td class="product-price">
							{% if item.amount['grossPriceAllTaxes'] != item.amount['priceNetAllTaxes'] %}
							<span class="price">
								<span style="text-decoration: line-through; font-size: 0.80em; color: #aaa;">{{ item.amount['grossPriceAllTaxes']|number_format(2, ',', ' ') }} €</span>
								{{ item.amount['priceNetAllTaxes']|number_format(2, ',', ' ') }} €
							</span>
							{% else %}
								<span class="price">{{ item.amount['priceNetAllTaxes']|number_format(2, ',', ' ') }} €</span>
							{% endif %}
						</td>
						<td class="product-quantity">
							{{ item.qty }}
						</td>
						<td class="product-subtotal">{{ (item.amount['priceNetAllTaxes'] * item.qty)|number_format(2, ',', ' ') }} €</td>
						<td class="product-remove"><a href="{{ path('cart_dell_line', {'id' : key}) }}"><img src="{{ asset('img/delete.png') }}" width="13" height="16"></a></td>
					</tr>
					{% endfor %}
				</tbody>
				<tfoot>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td class="prixTotal">Montant total</td>
						<td class="prixTotal">{{ cartService.totalCart|number_format(2, ',', ' ') }} €</td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td style="text-align: right;">Port</td>
						<td>{{ (cartService.getShipping['price']+cartService.getShipping['taxes'])|number_format(2, ',', ' ') }} €</td>
						<td></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td class="prixTotal"><strong>Total commande</strong></td>
						<td class="prixTotal">{{ (cartService.totalCart + cartService.getShipping['price']+cartService.getShipping['taxes'])|number_format(2, ',', ' ') }} €<td>
						<td></td>
					</tr>
					<td>
						<td colspan="5" style="text-align: left; background-color: #f2f2f2;">
						<form name="form1" method="post" action="">
							<input type="checkbox" name="accept_cgv" id="accept_cgv">
							<label for="accept_cgv">Je déclare avoir pris connaissance des <a href="page/CGV_9.html" id="open-infobox">conditions générales de vente</a></label>
						</form>
						</td>
					</td>
				</tfoot>
			</table>
		<div class="choosePayment">
			{% if app.user.customers.addresses|length > 0 %}
			<p><strong>Veuillez choisir un mode de paiement ci-dessous :</strong></p>
			<table id="moyenPaiement">
			    {% for payment in payments %}
			    <tr>
			        <td><span class="moyenPaiementImg"><img src="{{ asset('img/payments/') }}{{ payment.logo }}" alt="" /></span></td>
			        <td><span class="moyenPaiementTitre">{{ payment.title }}</span><span class="moyenPaiementDescription">{{ payment.description }}</span></td>
			        <td>
				       	<div class="valideCommande">
			               	<p><a href="{{ path(payment.linkSubmit) }}" class="btn btn-primary">Choisir ce mode de paiement &raquo;</a></p>
			           	</div>
			        </td>
			    </tr>
			    {% endfor %}
			</table>
			{% endif %}
		</div>
		{% else %}
		<div>
			<p colspan="6">Votre panier est vide.</p>
		</div>
		{% endif %}
	</div>
{% endblock %}

templates/main/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Votre panier d'achat{% endblock %}
{% block introHome %}{% endblock %}
{% block main %}
	<div id="mainContent">
		<h1>Mon panier</h1>
		{% for label, messages in app.flashes %}
			{% for message in messages %}
				<div class="alert alert-{{label}}">
					{{message|raw}}
				</div>
			{% endfor %}
		{% endfor %}
		{% if cart|length > 0 %}
			<table id="contenuPanier">
				<thead>
					<tr class="title-top">
						<th>&nbsp;</th>
						<th style="text-align: center">Produit</th>
						<th>Prix Unitaire</th>
						<th>Quantité</th>
						<th>Total</th>
						<th>&nbsp;</th>				
					</tr>
				</thead>
				<tbody>
					{% for key, item in cart %}
					{# produit non vrac #}
						<td class="product-thumbnail">
							{% if key in images|keys %}
							<img src="{{ asset('img/p/') ~ images[key] }}" alt="{{ item.title }}">
							{% else %}
							<img src="{{ asset('img/p/fr.jpg') }}" alt="{{ item.title }}">
							{% endif %}
						</td>
						<td style="text-align: center;">
							<strong>
								{{ item.title }}
							</strong>
								{% if item.product.bulkQuantity > 1 %}
								<br><small><span style="color: #f00; display: inline-block; padding: 0 9px; border: solid 1px #d1d1d1; border-radius: 50%; font-weight: bold;">!</span> Commandable dans un carton réunissant {{ item.product.bulkQuantity }} articles</small>
								{% endif %}
						</td>
						<td class="product-price">
							{% if item.amount['grossPriceAllTaxes'] != item.amount['priceNetAllTaxes'] %}
							<span class="price">
								<span style="text-decoration: line-through; font-size: 0.80em; color: #aaa;">{{ item.amount['grossPriceAllTaxes']|number_format(2, ',', ' ') }} €</span>
								{{ item.amount['priceNetAllTaxes']|number_format(2, ',', ' ') }} €
							</span>
							{% else %}
								<span class="price">{{ item.amount['priceNetAllTaxes']|number_format(2, ',', ' ') }} €</span>
							{% endif %}
						</td>
						<td class="product-quantity">
							<div class="gestionQte">
									<a href="{{ path('cart_less', {'id' : key}) }}" class="qteMoins">-</a>{{ item.qty }}<a href="{{ path('cart_more', {'id' : key}) }}" class="qtePlus">+</a></div>
						</td>
						<td class="product-subtotal">{{ (item.amount['priceNetAllTaxes'] * item.qty)|number_format(2, ',', ' ') }}&nbsp;€</td>
						<td class="product-remove"><a href="{{ path('cart_dell_line', {'id' : key}) }}"><img src="{{ asset('img/delete.png') }}" width="13" height="16"></a></td>
					</tr>
					{% endfor %}
					{# if bulk['exist'] == true #}
						{% if bulk['valid'] == false %}
						<tr>
							<td colspan="6">
								<p style="color: #F00;">Il vous manque des articles pour atteindre les conditionnements en vrac. Veuillez ajuster vos quantités ou <a href="">voir d'autres articles en vrac</a> pour compléter et valider votre panier.</p>
							</td>
						</tr>
						{% endif %}
					{# endif #}
				</tbody>
				<tfoot>
					<tr>
						<td></td>
						<td></td>
						<td class="prixTotal" colspan="2" style="text-align: right;">Montant total</td>
						<td class="prixTotal" style="text-align: right;">{{ cartService.totalCart|number_format(2, ',', ' ') }}&nbsp;€</td>
					</tr>
					{% set totalShipping = 0 %}
					{% for cartShipping in shipping %}
					{% set totalShipping = totalShipping + cartShipping['price'] + cartShipping['taxes'] %}
					<tr>
						<td></td>
						<td colspan="3" style="text-align: right;">Livraison {{ carriers[loop.index].carrierName }}</td>
						<td>{{ (cartShipping['price']+cartShipping['taxes'])|number_format(2, ',', ' ') }}&nbsp;€</td>
					</tr>
					{% endfor %}
					<tr>
						<td></td>
						<td></td>
						<td class="prixTotal" colspan="2" style="text-align: right;"><strong>Total commande</strong></td>
						<td class="prixTotal" style="text-align: right;">{{ (cartService.totalCart + totalShipping)|number_format(2, ',', ' ') }}&nbsp;€<td>
					</tr>
				</tfoot>
			</table>
		<div class="pleaseSubmit">
			<div class="validCart">
				{% if app.user %}
					<div class="valideCommande">
						{% if cartService.totalQuantity < 12 %}
							<p style="color: #DFDFDF;">Votre panier doit contenir un minimum de 12 articles</p>
						{% else %}
						<p><a href="{{ path('cart_confirm') }}">Valider votre commande&nbsp;&nbsp;&nbsp;&nbsp;></a></p>
						{% endif %}
					</div>
				{% else %}
				<div>
					<p>Veuillez <a href="{{ path('account_login') }}">vous identifier</a> ou <a href="{{ path('account_login') }}">créer votre compte</a> pour passer commande</p>
			    </div>
			    {% endif %}
			</div>
		</div>
		{% else %}
		<div>
			<p colspan="6">Votre panier est vide.</p>
		</div>
		{% endif %}
	</div>
{% endblock %}