src/Entity/MgProducts.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MgProductsRepository")
 */
class MgProducts
{
    //ENUM de la colonne discount_type
    const DISCOUNT_ON_AMOUNT = 'amount';
    const DISCOUNT_ON_PERCENT = 'percent';

    //ENUM de la colonne type
    const TYPE_MASTER = 'master';
    const TYPE_DOWNLOADABLE = 'downloadable';
    const TYPE_DOWNLOADABLE_EXCLU = 'downloadable_exclu';
    const TYPE_ATTRIBUT = 'attribut';

    private $discountTypeValues = array(
        self::DISCOUNT_ON_AMOUNT, self::DISCOUNT_ON_PERCENT
    );
    private $typeValues = array(
        self::TYPE_MASTER, self::TYPE_DOWNLOADABLE, self::TYPE_DOWNLOADABLE_EXCLU, self::TYPE_ATTRIBUT
    );

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $reference;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $purshasing_price;

    /**
     * @ORM\Column(type="float")
     */
    private $selling_price;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\MgTaxes", inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $taxe;

    /**
     * @ORM\Column(type="float")
     */
    private $selling_price_all_taxes;

    /**
     * @ORM\Column(type="integer")
     */
    private $sales_unit;

    /**
     * @ORM\Column(type="integer")
     */
    private $min_quantity;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $max_quantity;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $bulk_quantity;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $discount;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $discount_type;

    /**
     * @ORM\Column(type="boolean", options={"default": false}, nullable=true)
     */
    private $discount_on_taxe;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $stock_management;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $quantity;

    /**
     * @ORM\Column(type="boolean", options={"default": false}, nullable=true)
     */
    private $sell_out_of_stock;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $stock_alert;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $width;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $height;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $depth;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $weight;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\MgCarriers", inversedBy="products")
     */
    private $carrier;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $additionnal_shipping_cost;

    /**
     * @ORM\Column(type="boolean", nullable=true, options={"default": false})
     */
    private $pre_order;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $available_date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_publish;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $offline;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $type;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_add;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_up;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\MgUsers", inversedBy="productAdds")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\MgUsers", inversedBy="getProductsRevisers")
     */
    private $reviser;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\MgSuppliers", inversedBy="products")
     */
    private $supplier;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MgProductsLang", mappedBy="product", orphanRemoval=true)
     */
    private $contents;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\MgGammes", inversedBy="products")
     */
    private $gamme;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\MgProducts", inversedBy="mgProducts")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MgProducts", mappedBy="parent")
     */
    private $mgProducts;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\MgCategories", inversedBy="products")
     */
    private $categories;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MgProductsImages", mappedBy="product", orphanRemoval=true)
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MgMovementsStocks", mappedBy="product", orphanRemoval=true)
     */
    private $movementsStocks;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MgProductsNumerical", mappedBy="product", orphanRemoval=true)
     */
    private $numericals;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\MgAuthors", inversedBy="products")
     */
    private $authors;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MgPropertiesContents", mappedBy="product", orphanRemoval=true)
     */
    private $propertiesContents;

    public function __construct()
    {
        $this->reviser = new ArrayCollection();
        $this->date_add = new \Datetime();
        $this->available_date = new \Datetime();
        $this->date_publish = new \Datetime();
        $this->type = self::TYPE_MASTER;
        $this->contents = new ArrayCollection();
        $this->mgProducts = new ArrayCollection();
        $this->categories = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->movementsStocks = new ArrayCollection();
        $this->numericals = new ArrayCollection();
        $this->authors = new ArrayCollection();
        $this->propertiesContents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(?string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getPurshasingPrice(): ?float
    {
        return $this->purshasing_price;
    }

    public function setPurshasingPrice(?float $purshasing_price): self
    {
        $this->purshasing_price = $purshasing_price;

        return $this;
    }

    public function getSellingPrice(): ?float
    {
        return $this->selling_price;
    }

    public function setSellingPrice(float $selling_price): self
    {
        $this->selling_price = $selling_price;

        return $this;
    }

    public function getTaxe(): ?MgTaxes
    {
        return $this->taxe;
    }

    public function setTaxe(?MgTaxes $taxe): self
    {
        $this->taxe = $taxe;

        return $this;
    }

    public function getSellingPriceAllTaxes(): ?float
    {
        return $this->selling_price_all_taxes;
    }

    public function setSellingPriceAllTaxes(float $selling_price_all_taxes): self
    {
        $this->selling_price_all_taxes = $selling_price_all_taxes;

        return $this;
    }

    public function getSalesUnit(): ?int
    {
        return $this->sales_unit;
    }

    public function setSalesUnit(int $sales_unit): self
    {
        $this->sales_unit = $sales_unit;

        return $this;
    }

    public function getMinQuantity(): ?int
    {
        return $this->min_quantity;
    }

    public function setMinQuantity(int $min_quantity): self
    {
        $this->min_quantity = $min_quantity;

        return $this;
    }

    public function getMaxQuantity(): ?int
    {
        return $this->max_quantity;
    }

    public function setMaxQuantity(?int $max_quantity): self
    {
        $this->max_quantity = $max_quantity;

        return $this;
    }

    public function getBulkQuantity(): ?int
    {
        return $this->bulk_quantity;
    }

    public function setBulkQuantity(?int $bulk_quantity): self
    {
        $this->bulk_quantity = $bulk_quantity;

        return $this;
    }

    public function getDiscount(): ?float
    {
        return $this->discount;
    }

    public function setDiscount(?float $discount): self
    {
        $this->discount = $discount;

        return $this;
    }

    public function getDiscountType(): ?string
    {
        return $this->discount_type;
    }

    public function setDiscountType(?string $discount_type): self
    {
        if (!in_array($discount_type, $this->discountTypeValues)) {
            throw new \InvalidArgumentException(
                sprintf('Valeur invalide pour mg_products.discount_type : %s.', $discount_type)
            );
        }
        $this->discount_type = $discount_type;

        return $this;
    }

    public function getDiscountOnTaxe(): ?bool
    {
        return $this->discount_on_taxe;
    }

    public function setDiscountOnTaxe(?bool $discount_on_taxe): self
    {
        $this->discount_on_taxe = $discount_on_taxe;

        return $this;
    }

    public function getStockManagement(): ?bool
    {
        return $this->stock_management;
    }

    public function setStockManagement(bool $stock_management): self
    {
        $this->stock_management = $stock_management;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

src/Entity/MgTaxes.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MgTaxesRepository")
 */
class MgTaxes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $taxe_rate;

    /**
     * @ORM\Column(type="boolean")
     */
    private $taxe_active;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MgTaxesLang", mappedBy="taxe", orphanRemoval=true)
     */
    private $taxesLangs;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MgProducts", mappedBy="taxe")
     */
    private $products;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MgOrdersTaxes", mappedBy="taxe")
     */
    private $orderContentTaxes;

    public function __construct()
    {
        $this->taxesLangs = new ArrayCollection();
        $this->products = new ArrayCollection();
        $this->orderContentTaxes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTaxeRate(): ?float
    {
        return $this->taxe_rate;
    }

    public function setTaxeRate(float $taxe_rate): self
    {
        $this->taxe_rate = $taxe_rate;

        return $this;
    }

    public function getTaxeActive(): ?bool
    {
        return $this->taxe_active;
    }

    public function setTaxeActive(bool $taxe_active): self
    {
        $this->taxe_active = $taxe_active;

        return $this;
    }

    /**
     * @return Collection|MgTaxesLang[]
     */
    public function getTaxesLangs(): Collection
    {
        return $this->taxesLangs;
    }

    public function addTaxesLang(MgTaxesLang $taxesLang): self
    {
        if (!$this->taxesLangs->contains($taxesLang)) {
            $this->taxesLangs[] = $taxesLang;
            $taxesLang->setTaxe($this);
        }

        return $this;
    }

    public function removeTaxesLang(MgTaxesLang $taxesLang): self
    {
        if ($this->taxesLangs->contains($taxesLang)) {
            $this->taxesLangs->removeElement($taxesLang);
            // set the owning side to null (unless already changed)
            if ($taxesLang->getTaxe() === $this) {
                $taxesLang->setTaxe(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|MgProducts[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(MgProducts $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setTaxes($this);
        }

        return $this;
    }

    public function removeProduct(MgProducts $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getTaxes() === $this) {
                $product->setTaxes(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|MgOrdersTaxes[]
     */
    public function getOrderContentTaxes(): Collection
    {
        return $this->orderContentTaxes;
    }

    public function addOrderContentTax(MgOrdersTaxes $orderContentTax): self
    {
        if (!$this->orderContentTaxes->contains($orderContentTax)) {
            $this->orderContentTaxes[] = $orderContentTax;
            $orderContentTax->setTaxe($this);
        }

        return $this;
    }

    public function removeOrderContentTax(MgOrdersTaxes $orderContentTax): self
    {
        if ($this->orderContentTaxes->contains($orderContentTax)) {
            $this->orderContentTaxes->removeElement($orderContentTax);
            // set the owning side to null (unless already changed)
            if ($orderContentTax->getTaxe() === $this) {
                $orderContentTax->setTaxe(null);
            }
        }

        return $this;
    }
}

templates/main/catalog.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos vins{% endblock %}
{% block introHome %}{% endblock %}
{% block main %}
{#<div class="arianeCat">
	<ul>
	{% for ariane in filAriane %}
		<a href="{{ path('catalog', {'slug': ariane.slug}) }}" style="text-decoration: none;"><li>&nbsp;&nbsp;>&nbsp;&nbsp;{{ ariane.name }}</li></a>
	{% endfor %}
	</ul>
</div>#}
<aside id="listeCat" class="clearfix">
	<header>
		<h1>Nos vins</h1>
	</header>
	<nav>
		<ul class="sf-menu sf-vertical">
			{{ render(controller('App\\Controller\\MenusController::displayMenuCat')) }}
		</ul>
	</nav>
</aside>
<div id="mainContent" class="margeCompte">
	{% for product in products %}
	{% if product.type == 'master' %}
	<div class="blocBouteillesParCategorie">
		{% set slug = '' %}
		{% for content in product.contents %}
			{% if content.lang.id == 1 %}
				{% set slug = content.slug %}
			{% endif %}
		{% endfor %}
	<div id="produitCover">
		<a href="{{ path('product_detail', {'slug': slug}) }}">
		{% if product.id in imgPath|keys %}
			<img src="{{ asset('img/p/') ~ imgPath[product.id] }}" alt="{% for content in product.contents %}{% if content.lang.id == 1 %}{{ content.name }}{% endif %}{% endfor %}" style="max-height :100%">
		{% else %}
			<img src="{{ asset('img/p/fr.jpg') }}" alt="{% for content in product.contents %}{% if content.lang.id == 1 %}{{ content.name }}{% endif %}{% endfor %}">
		{% endif %}
		</a>
	</div>
	<div id="produitDescShort">
		<h2><a href="{{ path('product_detail', {'slug': slug}) }}">{% for content in product.contents %}{% if content.lang.id == 1 %}{{ content.name }}{% endif %}{% endfor %}</a></h2>
		<div class="resumeCourt">
			{% if product.bulkQuantity > 1 %}<small><span style="color: #f00; display: inline-block; padding: 0 9px; border: solid 1px #d1d1d1; border-radius: 5px; font-weight: bold;">Vente en vrac !</span></small>{% endif %}
			<p>{% for content in product.contents %}{% if content.lang.id == 1 %}{{ content.summary|raw }}{% endif %}{% endfor %}</p>
		</div>
	</div>
	<div class="zoneTarifProduit">
		<div class="lienDetail"><a href="{{ path('product_detail', {'slug': slug}) }}">>> D&eacute;couvrir ce vin</a></div>
			{% if product.sellingPriceAllTaxes > 0 %}
			<div class="zonePromo">
				{% set netprice = product.sellingPriceAllTaxes %}
				{% if product.discount != '' %}
				{% set netprice = product.discount|discountPriceAT(product.discountType, product.discountOnTaxe, '20', product.sellingPrice, product.sellingPriceAllTaxes) %}
				<div class="prixttcBrut">
					<del>{{ product.sellingPriceAllTaxes|number_format(2, ',', ' ') }} €</del>
				</div>
				<b> - {{ (netprice - product.sellingPriceAllTaxes)|number_format(2, ',', ' ') }} €</b>
				{% endif %}
			</div>
			<div class="prixttcNet">{{ product.sellingPriceAllTaxes|number_format(2, ',', ' ') }} €</div>
			{% if product.minQuantity > 1 %}<div id="prixpar6">soit {{ (product.minQuantity * netprice)|number_format(2, ',', ' ') }}&euro; les {{ product.minQuantity }} bouteilles</div>{% endif %}
			{% if product.propertiesContents|length > 0 %}
				{% for property in product.propertiesContents %}
					{% if property.lang.id == languagesService.languageDefault.id %}
					{% for propertie in properties %}
						{% if property.property.id == propertie.id %}
							<p class="prix" style="background-color: #009F49;">{% for content in propertie.properties %}{{ content.name }}{% endfor %} : {{ property.value|number_format(2, ',', ' ') }} €</p>
						{% endif %}
					{% endfor %}
					{% endif %}
				{% endfor %}
			{% endif %}
			{% endif %}
		</div>
	</div>
	{% endif %}
	{% else %}
		<p>Il n'y a pas encore d'article pour cette catégorie.</p>
	{% endfor %}
	{% if pagination == true %}
		<div id="pagination" style="clear: both;">
			<ul class="pagination justify-content-center">
				{% if page == 1 %}
					<li class="disabled">< Précédent</li>
				{% else %}
				<li class="page-item">
					{% if slugCat == false %}
					<a class="page-link" href="{{ path('catalog-by-cat', {'cat': getCat, 'page': page - 1}) }}">
						<i class="zmdi zmdi-chevron-left">< Précédent</i>
					</a>
					{% else %}
					<a class="page-link" href="{{ path('catalog', {'slug': slugCat, 'page': page - 1})}}">
						<i class="zmdi zmdi-chevron-left">< Précédent</i>
					</a>
					{% endif %}
				</li>
				{% endif %}
				{% for i in 1..pages %}
				<li class="page-item{% if page == i %} active{% endif %}">
					{% if slugCat == false %}
					<a class="page-link" href="{{ path('catalog-by-cat', {'cat': getCat, 'page': i}) }}">
						{{ i }}
					</a>
					{% else %}
					<a class="page-link" href="{{ path('catalog', {'slug': slugCat, 'page': i})}}">{{ i }}</a>
					{% endif %}
				</li>
				{% endfor %}
				{% if page == pages %}
					<li class="disabled">> Suivant</li>
				{% else %}
				<li class="page-item {% if page == pages %}disabled{% endif %}">
					{% if slugCat == false %}
					<a class="page-link" href="{{ path('catalog-by-cat', {'cat': getCat, 'page': page + 1}) }}">
						<i class="zmdi zmdi-chevron-right">> Suivant</i>
					</a>
					{% else %}
					<a class="page-link" href="{{ path('catalog', {'slug': slugCat, 'page': page + 1})}}">
						<i class="zmdi zmdi-chevron-right">> Suivant</i>
					</a>
					{% endif %}
				</li>
				{% endif %}
			</ul>
		</div>
	{% endif %}
{% endblock %}

templates/main/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pour nous contacter{% endblock %}
{% form_theme form _self %}
	{% block stylesheets %}
	<style>
		fieldset {
			border: none;
		}
		#contact_civility {
			display: flex;
			padding: 15px 0 0 15px;
		}
		#contact_civility .form-check {
			margin-right: 2.25em;
			/*float: left;*/
		}
		#contact_civility .form-check label {
			padding-left: 0;
			/*float: left;*/
		}
	</style>
	{% endblock %}
{% block main %}
	<h1>Contactez-nous !</h1>
	<aside id="donnees_contact">
		<div class="adressePostal">
			<h2>Pour nous écrire</h2>
			{% for address in addresses %}
				<p class="titre">
				{% for title in address.addressesTitles %}
					{% if title.lang.id == 1 %}
						{{ title.addressTitle }}
					{% endif %}
				{% endfor %}
				</p>
				<p class="street-address">{{ address.address }}</p>
				<p><span class="postal-code">{{ address.zipcode }}</span> <span class="locality">{{ address.town }}</span></p>
				<p class="tel"><b>Téléphone :</b>{{ address.phone }}</p>
				<hr>
			{% endfor %}
		</div>
	</aside>
	<section id="formulaire_contact" style="margin-left: 250px;">
		<p style="border-bottom: solid 1px #999999;">Besoin d'un conseil ? D'une information ? N'hésitez pas à nous contacter en utilisant le formulaire ci-dessous.</p>
		{% for label, messages in app.flashes %}
			{% for message in messages %}
				<p class="error">
					{{message|raw}}
				</p>
			{% endfor %}
		{% endfor %}
		{{ form_start(form) }}
			<p>
				{{ form_row(form.civility) }}
			<p>
			<p>
				{{ form_row(form.name) }}
			</p>
			<p>
				{{ form_row(form.firstname) }}
			</p>
			<p>
				{{ form_row(form.email) }}
			</p>
			<p>
				{{ form_row(form.phone) }}
			</p>
			<p>
				{{ form_row(form.subject) }}
			</p>
			<p>
				{{ form_row(form.message) }}
			</p>
			<small class="text-muted">En soumettant ce formulaire, les informations saisies peuvent être traitées dans le cadre d'une relation commerciale qui peut en découler.<br>Toutefois, les informations renseignées dans le formulaire restent strictement privées : {{ appService.params.title }} ne les enregistrent pas dans une base de données et elles ne seront transmises à aucun tiers.</small>
			<div class="contact-btn">
				<button type="submit" class="btn btn-primary">Envoyer</button>
			</div>
			{{ form_end(form) }}
		</div>
	</section>
{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}
{% block main %}
<div id="mainContent">
</div><!-- FIN DU #mainContent -->
{% endblock %}

templates/main/page.html.twig
{% extends 'base.html.twig' %}
{% set title = '' %}
{% set content = '' %}
	{# si la page est null, c'est qu'on appel les partenaires #}
	{% if page == null %}
		{% set title = 'Nos partenaires' %}
		{% set content = '' %}
	{% else %}
		{% for lang in page.contents %}
			{% set title = lang.title %}
			{% set content = lang.content %}
		{% endfor %}
	{% endif %}
{% block title %}{{ title }}{% endblock %}
{% block main %}
	<div id="listePartenaires">
		{% for supplier in suppliers %}
		<div>
			<figure>
				<span><img src="{{ asset('uploads/suppliers/') ~ supplier.id }}/{{supplier.supplierLogo }}" alt="{{ supplier.supplierName }}" style="max-width: 100%;"></span>
				<figcaption>
					{{ supplier.supplierName }}
				</figcaption>
			</figure>
		</div>
		{% else %}
		<p>Aucun partenaire.</p>
		{% endfor %}
	</div>
{% endblock %}

templates/main/product.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ content.name }}{% endblock %}
{% block introHome %}{% endblock %}
{% block main %}
<aside id="listeCat" class="clearfix">
	<header>
		<h1>Nos vins</h1>
	</header>
	<nav>
		<ul class="sf-menu sf-vertical">
			{{ render(controller('App\\Controller\\MenusController::displayMenuCat')) }}
		</ul>
	</nav>
</aside>
<div class="contentDetailProduit clearfix">
	<div class="ficheProduit">
		<h2>{{ content.name }}</h2>
		<div class="tarifProduit">
			{% set netprice = product.sellingPriceAllTaxes %}
			{% if product.discount != '' %}
			{% set netprice = product.discount|discountPriceAT(product.discountType, product.discountOnTaxe, '20', product.sellingPrice, product.sellingPriceAllTaxes) %}
				<del>
					{{ product.sellingPriceAllTaxes|number_format(2, ',', ' ') }} €
					<span class="remiseMontant">
						{{ product.discount|discountPriceAT(product.discountType, product.discountOnTaxe, taxe.taxeRate, product.sellingPrice, product.sellingPriceAllTaxes)|number_format(2, ',', ' ') }} €
					</span>
				</del>
			{% endif %}
			<p class="prixttc">{{ product.sellingPriceAllTaxes|number_format(2, ',', ' ') }} € TTC</p>
			{% if product.minQuantity > 1 %}<small>Soit {{ (product.minQuantity * netprice)|number_format(2, ',', ' ') }}&euro; les {{ product.minQuantity }} bouteilles</small>{% endif %}
			{% if product.bulkQuantity > 1 %}<small><span style="color: #f00; display: inline-block; padding: 0 9px; border: solid 1px #d1d1d1; border-radius: 5px; font-weight: bold;">Vente en vrac !</span> Disponible à l'unité, mais vendu dans un carton contenant au moins {{ product.bulkQuantity }} articles.</small>{% endif %}
		</div>
		<form method="post" enctype="multipart/form-data" action="{{ path('cart_add') }}">
				<label for="qte">Quantité</label>
				<input name="qty" type="number" id="qty" value="{{ product.minQuantity }}" style="width: 50px;" min="{{ product.minQuantity }}" step="{{ product.salesUnit }}" />
				<input type="hidden" name="version" value="physique">
				<input type="hidden" name="add_cart" value="{{ product.id }}">
				<div class="addtocart__actions">
					<input type="submit" name="addCart" id="addCart_0" class="tocart" value="Ajouter au panier">
				</div>
		</form>
		<div class="description">
			{{ content.description|raw }}
		</div>
	</div>
	<div class="visuelProduit clearfix">
		<div class="imagesProduits">
			<p class="imageCouverture">
				{% if imgCover != '' %}
				<a href="{{ asset('img/p/') ~ imgCoverOrigin }}" title="{{ content.name }}"><img src="{{ asset('img/p/') ~ imgCover }}" alt="{{ content.name }}"></a>
					{% if imgSecondary|length > 0 %}
						{% for key, otherImg in imgSecondary %}
						<p class="imagesComplementaire">
						<span>
							<a href="{{ asset('img/p/') ~ imgSecondaryOrigin[key] }}"><img src="{{ asset('img/p/') ~ otherImg }}" alt="{{ content.name }}"></a>
						</span>
						</p>
						{% endfor %}
					{% endif %}
				{% else %}
				<img src="{{ asset('img/p/fr.jpg') }}" alt="{{ content.name }}">
				{% endif %}
			</p>
		</div>
	</div>
</div>
{% endblock %}